# Generated by Django 5.1.2 on 2024-10-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_body_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
