# Generated by Django 5.1.2 on 2024-10-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_id',
            field=models.CharField(default='R0', editable=False, max_length=10, unique=True),
        ),
    ]
