# Generated by Django 5.1.2 on 2024-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_review_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
