# Generated by Django 5.1.2 on 2024-11-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_ticket_review_alter_review_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='review',
        ),
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.ticket'),
        ),
    ]
